/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {MarvelCharacter} from './character';


export interface MarvelCharacterDataContainer {
    offset?: number;
    limit?: number;
    total?: number;
    count?: number;
    results?: Array<MarvelCharacter>
}

