/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MarvelCharacterSummary { 
    /**
     * The path to the individual character resource.
     */
    resourceURI?: string;
    /**
     * The full name of the character.
     */
    name?: string;
    /**
     * The role of the creator in the parent entity.
     */
    role?: string;
}

