/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {MarvelImage} from './image';
import {MarvelSeriesList} from './seriesList';
import {MarvelComicList} from './comicList';

import {MarvelEventList} from './eventList';
import {MarvelStoryList} from './storyList';


export interface MarvelCharacter {
    id?: number;
    /**
     * The name of the character.
     */
    name?: string;
    /**
     * A short bio or description of the character.
     */
    description?: string;
    modified?: Date;
    /**
     * The canonical URL identifier for this resource.
     */
    resourceURI?: string;
    urls?: Array<string>
    thumbnail?: MarvelImage;
    comics?: MarvelComicList;
    stories?: MarvelStoryList;
    events?: MarvelEventList;
    series?: MarvelSeriesList;
}

