/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {MarvelImage} from './image';
import {MarvelSeriesList} from './seriesList';
import {MarvelComicList} from './comicList';

import {MarvelEventList} from './eventList';
import {MarvelStoryList} from './storyList';


export interface MarvelCreator {
    id?: number;
    /**
     * The first name of the creator.
     */
    firstName?: string;
    /**
     * The middle name of the creator.
     */
    middleName?: string;
    /**
     * The last name of the creator.
     */
    lastName?: string;
    /**
     * The suffix or honorific for the creator.
     */
    suffix?: string;
    /**
     * The full name of the creator (a space-separated concatenation of the above four fields).
     */
    fullName?: string;
    modified?: Date;
    /**
     * The canonical URL identifier for this resource.
     */
    resourceURI?: string;
    urls?: Array<string>
    thumbnail?: MarvelImage;
    series?: MarvelSeriesList;
    stories?: MarvelStoryList;
    comics?: MarvelComicList;
    events?: MarvelEventList;
}

