/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {MarvelCreatorList} from './creatorList';
import {MarvelImage} from './image';
import {MarvelSeriesList} from './seriesList';
import {MarvelEventSummary} from './eventSummary';
import {MarvelComicList} from './comicList';

import {MarvelCharacterList} from './characterList';
import {MarvelStoryList} from './storyList';


export interface MarvelEvent {
    id?: number;
    /**
     * The title of the event.
     */
    title?: string;
    /**
     * A description of the event.
     */
    description?: string;
    /**
     * The canonical URL identifier for this resource.
     */
    resourceURI?: string;
    urls?: Array<string>
    modified?: Date;
    start?: Date;
    end?: Date;
    thumbnail?: MarvelImage;
    comics?: MarvelComicList;
    stories?: MarvelStoryList;
    series?: MarvelSeriesList;
    characters?: MarvelCharacterList;
    creators?: MarvelCreatorList;
    next?: MarvelEventSummary;
    previous?: MarvelEventSummary;
}

