/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {MarvelEventDataContainer} from './eventDataContainer';


export interface MarvelEventDataWrapper {
    code?: number;
    /**
     * A string description of the call status.
     */
    status?: string;
    /**
     * The copyright notice for the returned result.
     */
    copyright?: string;
    /**
     * The attribution notice for this result.  Please display either this notice or the contents of the attributionHTML field on all screens which contain data from the Marvel Comics API.
     */
    attributionText?: string;
    /**
     * An HTML representation of the attribution notice for this result.  Please display either this notice or the contents of the attributionText field on all screens which contain data from the Marvel Comics API.
     */
    attributionHTML?: string;
    data?: MarvelEventDataContainer;
    /**
     * A digest value of the content returned by the call.
     */
    etag?: string;
}

