/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {MarvelCreatorList} from './creatorList';
import {MarvelImage} from './image';
import {MarvelSeriesSummary} from './seriesSummary';
import {MarvelComicList} from './comicList';

import {MarvelCharacterList} from './characterList';
import {MarvelEventList} from './eventList';
import {MarvelStoryList} from './storyList';


export interface MarvelSeries {
    id?: number;
    /**
     * The canonical title of the series.
     */
    title?: string;
    /**
     * A description of the series.
     */
    description?: string;
    /**
     * The canonical URL identifier for this resource.
     */
    resourceURI?: string;
    urls?: Array<string>
    startYear?: number;
    endYear?: number;
    /**
     * The age-appropriateness rating for the series.
     */
    rating?: string;
    modified?: Date;
    thumbnail?: MarvelImage;
    comics?: MarvelComicList;
    stories?: MarvelStoryList;
    events?: MarvelEventList;
    characters?: MarvelCharacterList;
    creators?: MarvelCreatorList;
    next?: MarvelSeriesSummary;
    previous?: MarvelSeriesSummary;
}

