/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {MarvelCreatorList} from './creatorList';
import {MarvelComicSummary} from './comicSummary';
import {MarvelImage} from './image';
import {MarvelSeriesList} from './seriesList';
import {MarvelComicList} from './comicList';

import {MarvelCharacterList} from './characterList';
import {MarvelEventList} from './eventList';


export interface MarvelStory {
    id?: number;
    /**
     * The story title.
     */
    title?: string;
    /**
     * A short description of the story.
     */
    description?: string;
    /**
     * The canonical URL identifier for this resource.
     */
    resourceURI?: string;
    /**
     * The story type e.g. interior story, cover, text story.
     */
    type?: string;
    modified?: Date;
    thumbnail?: MarvelImage;
    comics?: MarvelComicList;
    series?: MarvelSeriesList;
    events?: MarvelEventList;
    characters?: MarvelCharacterList;
    creators?: MarvelCreatorList;
    originalissue?: MarvelComicSummary;
}

