/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MarvelStorySummary { 
    /**
     * The path to the individual story resource.
     */
    resourceURI?: string;
    /**
     * The canonical name of the story.
     */
    name?: string;
    /**
     * The type of the story (interior or cover).
     */
    type?: string;
}

