/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MarvelTextObject { 
    /**
     * The canonical type of the text object (e.g. solicit text, preview text, etc.).
     */
    type?: string;
    /**
     * The IETF language tag denoting the language the text object is written in.
     */
    language?: string;
    /**
     * The text.
     */
    text?: string;
}

